version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: gaza_impact_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: gaza_impact_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
